root: true

extends: airbnb-base

rules:
  arrow-parens: [2, as-needed]
  no-console: 0
  no-underscore-dangle: 0
  no-restricted-syntax: [0, ForOfStatement]
  import/no-extraneous-dependencies: 0
  import/no-unresolved: 0

